### PR TITLE
Added support for .NET Standard

### PR DESCRIPTION
**Pull request by eriove**
Not sure if you accept pull requests?

I needed support for .NET Standard for one of my projects so I converted the project to the new VS2017 project format (to have support for multiple target frameworks). Since it is LGPL I thought it would be easiest to share my changes with a pull request.

I also had to create a new `PointF` for .NET Standard to compile and changed from .NET 3.5 to 2.0 since the project compiles for 2.0 too.

### CODE REVIEW

**Comment by Yaqiang** [comment]
Thanks and welcome for pull requests. I will review the code at free time.

**Comment by eriove** [comment]
Thanks!

**Comment by Yaqiang** [comment]
Sorry for so late code review and merge. I am quite busy in these days.

**Comment by eriove** [comment]
No problem :-)

**Pull request merged**
